version: '3'
services:
  attacker:
    container_name: attack-server
    build: ../Attack-Server
    ports:
      - "5001:5001"
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
  web:
    container_name: web-cache-poisoning
    build: .
    entrypoint: python3 web-cache-poisoning.py
    depends_on:
      - attacker
      - redis
    env_file:
      - .env
    ports:
      - "5000:5000"
